/// ⚠️ AUTOGENERATED CODE. DO NOT EDIT.
import SwiftUI
import Photos


func registerTestViews() {
   collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 8) {
    
            TabView {
                NavigationStack {
                    Text("First Text")
                    Button(action: {}) {
                        Text("Button")
                    }.padding()
                    Text("Second Text")
                    List([1, 2, 3, 4], id: \.self) { number in
                        Text("\(number)")
                    }
                    .navigationTitle("Test App")
                }
                .tabItem {
                    Text("First Tab")
                }

                Text("Second Page")
                    .tabItem {
                        Text("Second Tab")
                    }
            }
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 66) {
    
            TabView {
                NavigationStack {
                    Text("First Text")
                    Button(action: {}) {
                        Text("Button")
                    }.padding()
                    Text("Second Text")
                    List([1, 2, 3, 4], id: \.self) { number in
                        Text("\(number)")
                    }
                    .navigationTitle("Test App")
                }
                .tabItem {
                    Text("First Tab")
                }

                Text("Second Page")
                    .tabItem {
                        Text("Second Tab")
                    }
            }
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 108) {
    
            Text("First Text")
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 127) {
    
            Text("First Text")
            Text("Conditional Second Text")
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 135) {
    
            Text("First Text")
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 153) {
    
            Text("First Text")
            Text("Second Text")
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 162) {
    
            Text("First Text")
            Text("Second Text")
        
}
collect(fileName: "/SisyphosTests/PageHierarchyTests.swift", line: 182) {
    
            Text("First Text")
            Text("Alternative Second Text")
        
}
collect(fileName: "/SisyphosTests/SwitchTests.swift", line: 8) {
    
            Toggle("Some Toggle", isOn: binding(initialValue: false))
        
}
collect(fileName: "/SisyphosTests/SwitchTests.swift", line: 22) {
    
            Toggle("", isOn: binding(initialValue: false))
                .accessibilityIdentifier("the_switch")
        
}
collect(fileName: "/SisyphosTests/CollectionViewTests.swift", line: 8) {
    
            List {
                Text("First Cell")
                Group {
                    Text("Second Cell")
                    Text("Still Second Cell")
                }
                SwiftUI.Button("Third Cell", action: {})
            }
        
}
collect(fileName: "/SisyphosTests/StaticTextTests.swift", line: 8) {
    
            Text("Hello")
        
}
collect(fileName: "/SisyphosTests/StaticTextTests.swift", line: 22) {
    
            Text("Hello")
                .accessibilityIdentifier("the_text")
        
}
collect(fileName: "/SisyphosTests/SecureTextFieldTests.swift", line: 8) {
    
            SecureField("Enter password", text: binding(initialValue: ""))
        
}
collect(fileName: "/SisyphosTests/SecureTextFieldTests.swift", line: 22) {
    
            SecureField("Enter password", text: binding(initialValue: ""))
                .accessibilityIdentifier("the_securefield")
        
}
collect(fileName: "/SisyphosTests/InterruptionTests.swift", line: 17) {
    
            Button(action: {
                UIApplication.shared.accessibilityLabel = "Button was pressed"
            }) {
                Text("The Button")
            }
            .alert(
                "Some Alert",
                isPresented: binding(initialValue: true),
                actions: {
                    Button(action: {}) { Text("OK") }
                },
                message: {
                    Text("This is some alert.")
                }
            )
        
}
collect(fileName: "/SisyphosTests/InterruptionTests.swift", line: 66) {
    
            Button(action: {
                UIApplication.shared.accessibilityLabel = "Button was pressed"
            }) {
                Text("The Button")
            }
            .onAppear {
                PHPhotoLibrary.requestAuthorization(for: .addOnly) { _ in }
            }
        
}
collect(fileName: "/SisyphosTests/InterruptionTests.swift", line: 97) {
    
            Text("Test for denying")
                .onAppear {
                    PHPhotoLibrary.requestAuthorization(for: .addOnly) { status in
                        UIApplication.shared.accessibilityLabel = "\(status)"
                    }
                }
        
}
collect(fileName: "/SisyphosTests/InterruptionTests.swift", line: 112) {
    
            Text("Test for denying")
                .onAppear {
                    PHPhotoLibrary.requestAuthorization(for: .addOnly) { status in
                        UIApplication.shared.accessibilityLabel = "\(status)"
                    }
                }
        
}
collect(fileName: "/SisyphosTests/NavigationBarTests.swift", line: 9) {
    
            NavigationStack {
                Text("Welcome!")
                    .navigationTitle("Hello NavigationBar!")
            }
        
}
collect(fileName: "/SisyphosTests/NavigationBarTests.swift", line: 28) {
    
            NavigationStack(path: binding(initialValue: [1, 2, 3, 4])) {
                Group {
                    Text("Initial Page")
                    NavigationLink("Let's start", value: 1)
                }
                .navigationTitle("Start")
                    .navigationDestination(for: Int.self) { number in
                        Text("Page \(number)")
                            .navigationTitle("Page \(number)")
                        NavigationLink("next page", value: number + 1)
                    }
            }
        
}
collect(fileName: "/SisyphosTests/AlertTests.swift", line: 8) {
    
            Text("App")
            .alert(
                "Some Alert",
                isPresented: binding(initialValue: true),
                actions: {
                    Button(action: {}) { Text("OK") }
                },
                message: {
                    Text("This is some alert.")
                }
            )
        
}
collect(fileName: "/SisyphosTests/ButtonTests.swift", line: 8) {
    
            SwiftUI.Button(action: {}) {
                Text("Some Button")
            }
            .accessibilityIdentifier("some_button")
        
}
collect(fileName: "/SisyphosTests/ButtonTests.swift", line: 25) {
    
            SwiftUI.Button(action: {}) {
                Text("Some Button")
            }
            .accessibilityIdentifier("some_button")
        
}
collect(fileName: "/SisyphosTests/ButtonTests.swift", line: 42) {
    
            SwiftUI.Button(action: {}) {
                Text("Some Button")
            }
            .accessibilityIdentifier("some_button")
        
}
collect(fileName: "/SisyphosTests/ButtonTests.swift", line: 59) {
    
            SwiftUI.Button(action: {
                UIApplication.shared.accessibilityLabel = "Button tapped"
            }) {
                Text("Some Button")
            }
            .accessibilityIdentifier("some_button")

            SwiftUI.Button(action: {}) {
                Text("Button that should not be matched")
            }
        
}
collect(fileName: "/SisyphosTests/PageExistsErrorTests.swift", line: 8) {
    
            Text("Text")
        
}
collect(fileName: "/SisyphosTests/PageExistsErrorTests.swift", line: 24) {
    
            Text("Text")
        
}
collect(fileName: "/SisyphosTests/TestDataTests.swift", line: 8) {
    
            Text("Test: Some Value")
        
}
collect(fileName: "/SisyphosTests/TestDataTests.swift", line: 26) {
    
            SwiftUI.Button("Buy now for 7.77 EUR", action: {})
        
}
collect(fileName: "/SisyphosTests/TextFieldTests.swift", line: 9) {
    
            SwiftUI.TextField("Enter text", text: appValueBinding())
                .accessibilityIdentifier("the_textfield")
        
}
collect(fileName: "/SisyphosTests/TextFieldTests.swift", line: 24) {
    
            SwiftUI.TextField("Enter text", text: binding(initialValue: "Some Value"))
                .accessibilityIdentifier("the_textfield")
        
}
collect(fileName: "/SisyphosTests/TextFieldTests.swift", line: 39) {
    
            Text("Some Text")
            SwiftUI.TextField("Enter text", text: appValueBinding())
                .accessibilityIdentifier("the_textfield")
            Button("Some button", action: {})
        
}
collect(fileName: "/SisyphosTests/TextFieldTests.swift", line: 56) {
    
            SwiftUI.TextField("Enter text", text: appValueBinding())
        
}
collect(fileName: "/SisyphosTests/TextFieldTests.swift", line: 76) {
    
            SwiftUI.TextField("Enter text", text: appValueBinding())
        
}
collect(fileName: "/SisyphosTests/TabBarTests.swift", line: 9) {
    
            TabView {
                Text("First Screen")
                    .tabItem {
                        Text("First")
                    }
                Text("Second Screen")
                    .tabItem {
                        Text("Second")
                    }
            }
        
}
collect(fileName: "/SisyphosTests/TabBarTests.swift", line: 36) {
    
            TabView {
                Text("First Screen")
                    .tabItem {
                        Text("First")
                    }
                Text("Second Screen")
                    .tabItem {
                        Text("Second")
                    }
            }
        
}

}